export const iconNames = {
  clear: "clear",
  clouds: "clouds",
  drizzle: "drizzle",
  rain: "rain",
  snow: "snow",
  thunderstorm: "thunderstorm",
  wind_outline: "wind_outline",
  humidity_outline: "humidity_outline",
  rain_outline: "rain_outline",
  sunset_outline: "sunset_outline",
  temperature_outline: "temperature_outline",
  search_outline: "search_outline",
  home_outline: "home_outline",
  menu_outline: "menu_outline",
};
